### ISSUE TITLE
Example of background / foreground

### ISSUE THREAD

**Issue by eried** [drifkind/QDispatch#1]
What would be the way to follow what you say in this section of the readme? about just keeping the structure unaltered except the delays and the call to run() on the loop?

Could you add a simple example of this?

BTW: this is one of the few cooperative multitask libraries that actually work with SparkFun Artemis modules without any issue :)

**Comment by drifkind** [comment]
I’m traveling now—I’ll get back to you when I figure out where I am. —D

**Comment by eried** [comment]
No worries I think I figured what you meant by that section. I am just calling delay and run. Works flawless, but I have another question now :)
