### ISSUE TITLE
External library

### ISSUE THREAD

**Issue by eried** [drifkind/QDispatch#2]
Hi again,

I am using this for a satellital tracker and the library I am using (IridiumSBD.h) has some long waiting functions... (i.e. Send message to the satellite), so ofc it blocks the whole "thread". 

What would be your approach to make an external library like IridiumSBD _QDispatch-able_?

**Comment by drifkind** [comment]
It's hard to do anything with that except by using an actual threading library (which is/are available). Even then you have to look closely at the library to make sure it can be thread-safe. The closest I got with QDispatch was making EventBarrier::signal thread-safe, so it could be called from an interrupt handler. (That hasn't made it into the release yet.)

It's possible you'd find the library thread-safe with no changes, but it could also be so unsafe that no one can fix it. You never know till you look.

David

(Still traveling, need about 48 hours more sleep.)

**Comment by eried** [comment]
Oh, enjoy your trip! lol!

Anyways, maybe then an option would be to pass the dispatcher when initializing that library and make it use your library. But I am slightly confused maybe you could give me a hint after you sleep :)

I would share the dispatcher:
![image](https://user-images.githubusercontent.com/1091420/95559486-20294300-0a18-11eb-9f4c-a8242948129f.png)

And then just call `dispatcher.run()` on locking operations inside that library? What you think in that approach?

**Comment by eried** [comment]
:P I can close this also, it is not the prettiest hack but it worked

https://github.com/innovationgarage/SparkFun_IridiumSBD_I2C_Arduino_Library/commit/5d98675db4e6f4312860c6aeb9250b26e493d334
